title: "Gallery"
description: |
  These are photo arrays that are only used within the gallery to display images.

patterns:
  project:
    title: "Project Gallery"
    description: |
      This gallery is used to display multiple images for the same project piece. To be used inside of the project gallery card.
    fields:
      - name: data
        type: object
        data:
          source: "site.portfolio-pieces[1]"
          type: portfolio-piece

  portfolio:
    title: "Portfolio Gallery"
    description: |
      This gallery is used to show all of the portfolio projects. To be used inside of the portfolio gallery card
    fields:
      - name: "data"
        type: "object"
        data:
          source: "site.portfolio-pieces[0]"
          type: "portfolio-piece"

  icon-array:
    title: "Icon Array"
    description: |
      Icon array is used to show all of the icons for the tools used to create each project. This array is used in the image card on the gallery page as well as in the project section on each portfolio-piece page.
    fields:
      - name: data
        type: object
        data:
          source: "site.portfolio-pieces[1]"
          type: portfolio-piece
