title: "Footers"
description: |
  Footers are to be used on every page.

patterns:
  footer:
    title: "Basic Footer"
    description: |
      The footer contains some privacy information and navigation. It should be used for most pages where the user should be able to navigate easily.
