title: "Buttons"
description: |

patterns:
  basic:
    title: "Basic button"
    description: |
      The basic button is to be used most of the time.
    fields:
      - name: 'text'
        type: 'string'
        example: 'View Projects'
      - name: 'url'
        type: 'string'
        example: '/design-projects/'

  ghost:
    title: "Ghost button"
    description: |
      The ghost button is to be used only when aesthetically necessary, such as for banners or for over images.
    fields:
      - name: 'text'
        type: 'string'
        example: 'View Projects'
      - name: 'url'
        type: 'string'
        example: '/design-projects/'
