title: "Header"
description: |
  The header should be used for all pages, and consists of the masthead (containing the navigation as well as the name mark). A simple decorative header to be used on all pages for consistency and clarity.
