title: "Forms"
description: |
  Forms are only used on the contact page, and only to send an email.
patterns:
  name:
    title: "Name Field"
    description: |
      Text-line fields are to be used for short text entries, in this case for the sender's name.
    fields:
      - name: label
        type: string
        example: "Your Full Name"
      - name: placeholder
        type: string
        example: "Please enter your name"
      - name: error
        type: string
        example: "This is a required field."
  email:
    title: "Email Address Field"
    description: |
      This is to be used for email addresses only.
    fields:
      - name: label
        type: string
        example: "Your Email Address"
      - name: placeholder
        type: string
        example: "email@email.com"
      - name: error
        type: string
        example: "Please enter your email address."
  details:
    title: "Email Details Field"
    description: |
      This is for the email body.
    fields:
      - name: label
        type: string
        example: "Comments"
      - name: placeholder
        type: string
        example: "Please type your comment, question, or request here."
      - name: error
        type: string
        example: "This is a required field."
  submit:
    title: "Submit Button"
    description: |
      This button is used to submit the email.
    fields:
      - name: text
        type: string
        example: "Send"
