patterns:
  project-gallery:
    title: "Project Gallery Card"
    description: |
      The Project Gallery Card is used to display each portfolio piece. It includes a more detailed description of each portfolio piece, as well as a gallery of images.
    fields:
      - name: "data"
        type: "object"
        data:
          source: "site.portfolio-pieces[1]"
          type: "portfolio-piece"

  image:
    title: "Image Card"
    description: |
      The image card is used on the gallery landing page to introduce each portfolio piece. It links to the portfolio viewer.
    width: 400px
    fields:
      - name: data
        type: object
        data:
          source: "site.portfolio-pieces[1]"
          type: portfolio-piece

  info:
    title: "Information Card"
    description: |
      The information card is used for displaying a section of text without any accompanying images.
    fields:
      - name: text
        type: string
        example: "View Projects"
      - name: url
        type: string
        example: "/design-projects/"
