patterns:
  project-gallery:
    title: "Project Gallery Card"
    description: |
      The Project Gallery Card is used to display each portfolio piece. It includes a more detailed description of each portfolio piece, as well as a gallery of images.
    fields:
      - name: "data"
        type: "object"
        data:
          source: "site.portfolio-pieces[0]"
          type: "portfolio-piece"

  image-button:
    title: "Image with button"
    description: |
      The image-button card is used on the gallery landing page to introduce each portfolio piece. It links to the portfolio viewer.
    fields:
      - name: "data"
        type: "object"
        data:
          source: "site.portfolio-pieces[0]"
          type: "portfolio-piece"
