title: "Banners"
description: |
  Banners should be used for main pages.

patterns:
  banner:
    title: "Basic Banner"
    description: |
      A simple decorative banner to be used when it is not ideal to direct the user to a different page. The function is decoration and continuity throughout non-gallery pages.

    fields:
      - name: heading
        type: string
        example: "Short relevant statement that grabs attention"
      - name: image
        type: string
        example: "/images/pastelpinkgreen.jpg"

  hero-image:
    title: "Hero Image Banner"
    description: |
      This banner must link to another page. It will be used on the home page to link to the projects gallery.

    fields:
      - name: heading
        type: string
        example: "Short relevant statement that grabs attention!"
      - name: image
        type: string
        example: "/images/pastelpinkgreen.jpg"
      - name: text
        type: string
        example: "longer relevant statement that reinforces call-to-action"
      - name: button-text
        type: string
        example: "View Projects"
      - name: button-url
        type: url
        example: "/design-projects/"
